# Generated by Django 5.0.2 on 2024-02-24 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("image_upload", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="imageupload",
            name="title",
        ),
    ]
